"""Initial migration

Revision ID: 36b66341fdd7
Revises: 
Create Date: 2026-05-16 22:39:13.148644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36b66341fdd7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employees_id', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_departments_id', table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('departments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint('char_length(name::text) >= 1', name='name_not_empty'),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], name='departments_parent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='departments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_departments_id', 'departments', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('hired_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint('char_length("position"::text) >= 1', name='position_not_empty'),
    sa.CheckConstraint('char_length(full_name::text) >= 1', name='full_name_not_empty'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='employees_department_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='employees_pkey')
    )
    op.create_index('ix_employees_id', 'employees', ['id'], unique=False)
    # ### end Alembic commands ###
